FROM node:20-alpine AS builder
WORKDIR /app
COPY apps/web/package.json apps/web/package-lock.json* ./
RUN npm install
COPY apps/web ./
RUN npm run build

FROM nginx:alpine
RUN apk add --no-cache iproute2
# Copy built static assets from React Vite app
COPY --from=builder /app/dist /usr/share/nginx/html
# Copy custom Nginx edge CDN configuration
COPY infra/nginx/cdn.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
