services:
  postgres:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  redis:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  kafka:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M

  kgs-service:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  url-service-1:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  url-service-2:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  analytics-service:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  load-balancer:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  mock-cdn:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
